# Generated by Django 5.2.1 on 2025-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
