# Generated by Django 5.2.1 on 2025-08-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_alter_projects_options_projects_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skill',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
